### ISSUE TITLE
Inconsistencies with clear and rewind

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#168] opened 2015-09-30 15:40 UTC
I noticed some strange behavior with the Rewind button, especially when introducing the clear function

1) open sim
2) start the orbit for the Sun and Earth
3) after the sim runs for a few seconds, switch to the next orbit. let it run for a few seconds
4) switch back to the initial orbit. Press rewind. 
5) the sim will start in it's initial position but the date will rewind to the time when you switched back to the sim. Thus it will not restart at 0 days but rather something like 70 days

Also some other weird behavior you can pause the sim and then press rewind. The date will not change but the positions will return to whatever they were initially. Additionally once the sim is paused one can clear the date and then press rewind. The date will not start at 0 days but rather return a different date. 

Tested on Windows 10, experimental.2

**Comment by aaronsamuel137** [comment] 2015-09-30 22:39
Both of these issues are present in the Java version too. @ariel-phet, are these something I should address?

**Comment by ariel-phet** [comment] 2015-10-01 14:57
@bryo5363 and @aaronsamuel137 I need to think about that one....I believe the "rewind" button is just to bring back to the same starting conditions....but that does seem confusing.

@arouinfar - thoughts on the above behavior? We might need to talk with @kathy-phet

**Comment by arouinfar** [comment] 2016-02-29 21:38
I agree with @ariel-phet that I think the intent of the rewind button is to bring the system back to its starting conditions. After playing with dev.24 and the Java version a bit, I've confirmed that the behaviors match, but I think the interaction feels inconsistent/buggy.

I've outlined a few test cases below. In all cases, the sim was freshly started, and the Earth was allowed to move around the Moon for a little while. 
* Click rewind. Earth Days <b>usually </b> resets to zero. Occasionally, I've pressed rewind in the 20-30 day range (sim had been freshly started) and the Earth Days displays something nonsensical like 68 days. This is not consistently reproducible, but has been observed in both Java and HTML5.
* Pause the sim, and take note of the number of Earth Days displayed (e.g. 45 days). If sim is subsequently unpaused then rewound (OR rewound and then unpaused -- order doesn't seem to matter) the number of days displayed matches whatever the state of the sim was when it was paused (e.g. 45 days). If paused/unpaused multiple times before rewinding, the time at the most recent pause event will be displayed upon rewind. 
* Switch to a different system, but take note of the number of Earth Days that have elapsed prior to switching (e.g. 62 days). Switch back to Moon/Earth, wait a few seconds, press rewind. The number of Earth Days displayed will be equal to the number of days at the time of the switch (e.g. 62 days).  If you switch between systems multiple times before rewinding, the time at the most recent switch event will be displayed upon rewind. 

When development resumes on this sim, the design team should revisit this issue and have a discussion about the desired behavior of the rewind feature. Marking as on-hold for now.

**Comment by jessegreenberg** [comment] 2016-08-17 22:35
I just noticed this issue as well while working on #162.  I also noticed the date seems buggy with Reset All.
Here is what I observed:
 - Let the earth orbit for any number of days.
 - Press Reset All button.
 - Let the earth orbit for any number of days.
 -  Press rewind
 - The date will now be the number of days when the user pressed reset all.

**Comment by arouinfar** [comment] 2016-08-25 17:21
@phet-steele and I discussed this issue a bit, and he's discovered that the play/pause button will change the saved state (stored date and positions) in unexpected ways. I believe he discussed his findings with @jessegreenberg already.

@phet-steele and I worked through the desired behavior together and came up with some new guidelines.

In general:
* The refresh button in the system selection panel will restore the default locations of the objects and reset the timer to zero. Checkbox selections will remain intact (e.g. if velocity vectors are on, they will remain on) but the actual values of velocity and mass will be set to default.
* Rewind will take the system back to its saved state, and the timer will reset to zero. Most of the time, this will be completely redundant of the refresh button in the system selection panel. There is one exception, described in more detail below.
* Clear will always reset the number of days/years to zero.
* Play/pause will not affect the saved state on its own.


Play/pause should not affect the saved state UNLESS the sim is paused, and the objects have been dragged, then dropped. After dropping the object, the timer should be set to 0. In this case, we might expect that users are setting up an experiment by moving the sun/earth/etc. that they may want to repeat like in this situation. The sim is paused, the sun is moved, and then the sim is played. 

![gao_manualchange](https://cloud.githubusercontent.com/assets/8419308/17977715/0dfe537a-6ab0-11e6-9d0d-22e31ba33a07.gif)

In cases like this, the state should be saved when the drag is ended. If the user presses the rewind button, the sim should reload in this state, and the the days should reset to zero.
![image](https://cloud.githubusercontent.com/assets/8419308/17977941/e7eb225c-6ab0-11e6-85c0-607ad9407c79.png)

It is unlikely that students are setting up an experiment they wish to repeat if they are dynamically moving the objects around while the sim is in play mode. Like this, for example:
![gao_dynamicchange](https://cloud.githubusercontent.com/assets/8419308/17978067/9c3a3b12-6ab1-11e6-9792-daa3aefcebdc.gif)

In cases like this, the rewind button would act like the reset button in the system selection panel. (Assuming there wasn't a previously saved state like my earlier example.)

**Comment by arouinfar** [comment] 2016-08-25 17:21
@kathy-phet this is the issue we were talking about during status.

**Comment by jessegreenberg** [comment] 2016-08-26 21:47
> Rewind will take the system back to its saved state, and the timer will reset to zero. 

Just to be clear, should rewind take the system back to its saved state and reset the timer to zero even when the time of the saved state wasn't zero?  So the date is *never* stored and will always be reset after an interaction with the system.

**Comment by phet-steele** [comment] 2016-08-26 21:53
> reset the timer to zero even when the time of the saved state wasn't zero?

@jessegreenberg there shouldn't be a case where the saved state does not begin at 0, so rewinding to the start of the saved state should display the timer as 0. From above:

>Play/pause should not affect the saved state UNLESS the sim is paused, and the objects have been dragged, then dropped. After dropping the object, the timer should be set to 0

**Comment by jessegreenberg** [comment] 2016-08-26 21:56
Great, thanks, I just wanted to make sure that the date should no longer be saved in any circumstance.

I am going to break this up into a checklist of TODO items from the above description of desired behavior.

- [ ] refresh button should restore the default locations/velocity of objects and reset timer to zero.
  - [ ] checkboxes should remain intact when refresh is pressed
- [ ] rewind should take system back to its saved state
- [ ] rewind should reset timer to zero
- [ ] Clear will always reset the number of days/years to zero
- [ ] Pausing is the way to save the state of the system
- [ ] Dropping an object while the sim is paused should reset the timer to zero

@arouinfar please add to this list if you notice anything missing.

**Comment by arouinfar** [comment] 2016-08-26 22:04
@jessegreenberg Looks pretty good. I updated the 2nd to last item about pausing. Pausing by itself will not save the state. Objects need to be moved the play space while the sim is paused to trigger a new saved state. The state will save once the object has been dropped (which is your last checklist item).

**Comment by jessegreenberg** [comment] 2016-08-29 16:57
@arouinfar and @phet-steele I think this is fixed in the commits above.  Here is a dev version with the fixes, would you mind reviewing to make sure everything is handled?

http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.28/gravity-and-orbits_en.html

**Comment by arouinfar** [comment] 2016-08-31 16:49
@jessegreenberg this generally looks pretty good! I've encountered just one issue with the Sun/Earth/Moon system.

If the Moon is obliterated before the state is saved, the rewind button will cause the Moon to appear in its default location like so:

![moon_respawn](https://cloud.githubusercontent.com/assets/8419308/18138099/64fcd928-6f68-11e6-8354-792433cbbd49.gif)

In this situation, the Moon should not reappear when rewind is pressed, since it was not present when the state was saved.

**Comment by jessegreenberg** [comment] 2016-10-26 19:18
The state is saved every time a body changes one if its properties while paused.  This is not efficient since we want to save the state when the user releases on drag.  In addition, only the single body state is saved when a particular body changes.  For instance, dragging the earth while paused will save the state of the earth, but none of the other body states will be saved unless one of their observable properties change (which is what is causing the issue in https://github.com/phetsims/gravity-and-orbits/issues/168#issuecomment-243827126).

The 'state saving'  needs to be handled more globally so that the entire system is saved when the user is setting up an experiment.

**Comment by jessegreenberg** [comment] 2016-10-26 19:41
Fixed in the above commit.  Rather than saving the state of individual bodies every time a property changes, the state of the whole system is saved after the user sets up an experiment.

**Comment by jessegreenberg** [comment] 2016-10-26 19:55
@arouinfar can you please verify that the behavior is correct in the latest version?
http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.31/gravity-and-orbits_en.html

**Comment by arouinfar** [comment] 2016-10-28 20:23
@jessegreenberg looks good to me!

**Closed by arouinfar** 2016-10-28 20:23 UTC
Labels: status:ready-for-review, status:ready-to-test, type:bug
