### ISSUE TITLE
Can GravityAndOrbitsPlayArea's MeasuringTapeNode.isTipDragBounded: false be removed?

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#281] opened 2019-08-27 00:24 UTC
From https://github.com/phetsims/wave-interference/issues/429 GravityAndOrbitsPlayArea.js has `new MeasuringTapeNode` with option: `isTipDragBounded: false,`.  It seems that option should be removed but it was unclear why it was there so I thought I should ask.  @jessegreenberg can you please take a look?

**Comment by jessegreenberg** [comment] 2019-08-29 17:32
I tracked this down to this commit https://github.com/phetsims/gravity-and-orbits/commit/709f17867d2002ff455a583c3d94c83955874e82, and it is not clear this was added. Majority of work for that commit was for something else. I will remove.

**Comment by jessegreenberg** [comment] 2019-08-29 17:33
Ah I see that the default for isTipDragBounded is now true. That seems most correct and I can't think of any reason that shouldn't apply to this sim too.

**Comment by jessegreenberg** [comment] 2019-08-29 17:34
It has been removed @samreid.

**Comment by jessegreenberg** [comment] 2019-08-29 19:42
Well, I realized this does change the behavior a little now that the default for `isTipDragBounded` is true. Measuring tape is limited to dev bounds and planets can fly out of those bounds. Previously you could still measure distances to planets out of bounds if the window was large enough. Now it is limited to this:
![image](https://user-images.githubusercontent.com/6396244/63970973-76852d80-ca73-11e9-9124-7f43aba33af2.png)

So I am inclined to set to false again if that is OK with you @samreid.

**Comment by samreid** [comment] 2019-08-29 21:47
How difficult would it be to make the drag bounds match the visible bounds, as is done in other sims like Wave Interference?

**Comment by samreid** [comment] 2019-10-17 02:36
After review, I determined it will be nontrivial based on existing implementation details to make the drag bounds match the visible bounds.  There is also the question of whether we would apply that expanded bounds to dragging the masses, or the return button display.  There is the further question about whether to extend the bounds to the right of the screen--at the moment they are limited by the left edge of the control panels.  In my opinion, the optimal design would be to expand all of the bounds to match the visible bounds.  However, since this work would be nontrivial I wanted to check in before starting on it.  @arouinfar or @ariel-phet how should we proceed?  Should this be done for next publication?

**Comment by ariel-phet** [comment] 2019-10-21 20:05
@samreid I do not think we should work on having the drag bounds match the visible bounds. Although that might well be nice, I don't believe we have received any teacher requests for such a feature change, so I do not think it is currently worth our time to make that kind of nontrivial change to the sim.

If we were going to invest time in improvements, I would be much more inclined to improve performance (to me, in the published version, the sim still runs just a bit chunky, as if garbage collections are occurring). If there are some ways to improve that performance without major changes, that would be a better use of time in my opinion.

**Comment by arouinfar** [comment] 2019-10-21 20:45
I agree with @ariel-phet. While it'd be nice if the drag bounds matched the visible bounds, it's not worth the investment of resources that a nontrivial change would require.

**Comment by samreid** [comment] 2022-09-06 02:06
It seems this was requested in https://github.com/phetsims/gravity-and-orbits/issues/416?  I'll close that one as duplicate and take another look.

**Comment by arouinfar** [comment] 2022-09-09 22:28
@samreid I was unable to reproduce the behavior described in #416, and it looks like the client didn't provide steps to reproduce the issue. However, #416 was related to https://github.com/phetsims/density-buoyancy-common/issues/67. In Density, the underlying issue was due to an abrupt change in the aspect ratio. The client guide now includes this caution:
> Keep the PhET-iO simulation at the same (or similar) aspect ratio as the end product while you are using Studio. Some simulations allow elements to float to the edges of the window to maximize the space for student exploration. When loading a customized simulation, it will resize to fit the browser/iframe aspect ratio. As a result, elements may shift to remain in the visible bounds.

I think we can go ahead and close this issue.

**Closed by arouinfar** 2022-09-09 22:28 UTC
Labels: type:question
