### ISSUE TITLE
CT matrix must be finite

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#375] opened 2021-01-08 16:35 UTC
```
gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610063879055%7D
Uncaught Error: Assertion failed: matrix must be finite
Error: Assertion failed: matrix must be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:85:15)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:98:11)
at ModelViewTransform2.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:96:20)
at ModelViewTransform2.setMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:74:10)
at ModelViewTransform2.setToRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:118:10)
at Function.createRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:238:38)
at PanZoomListener.sourceFramePanBoundsProperty.lazyLink.phetioDependencies (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PanZoomListener.js:77:64)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610078020345%7D
Uncaught Error: Assertion failed: matrix must be finite
Error: Assertion failed: matrix must be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:85:15)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:98:11)
at ModelViewTransform2.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:96:20)
at ModelViewTransform2.setMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:74:10)
at ModelViewTransform2.setToRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:118:10)
at Function.createRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:238:38)
at PanZoomListener.sourceFramePanBoundsProperty.lazyLink.phetioDependencies (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PanZoomListener.js:77:64)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610094132869%7D
Uncaught Error: Assertion failed: matrix must be finite
Error: Assertion failed: matrix must be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:85:15)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:98:11)
at ModelViewTransform2.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:96:20)
at ModelViewTransform2.setMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:74:10)
at ModelViewTransform2.setToRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:118:10)
at Function.createRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:238:38)
at PanZoomListener.sourceFramePanBoundsProperty.lazyLink.phetioDependencies (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PanZoomListener.js:77:64)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610108220263%7D
Uncaught Error: Assertion failed: matrix must be finite
Error: Assertion failed: matrix must be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:85:15)
at ModelViewTransform2.validateMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:98:11)
at ModelViewTransform2.invalidate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:96:20)
at ModelViewTransform2.setMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/dot/js/Transform3.js:74:10)
at ModelViewTransform2.setToRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:118:10)
at Function.createRectangleMapping (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/phetcommon/js/view/ModelViewTransform2.js:238:38)
at PanZoomListener.sourceFramePanBoundsProperty.lazyLink.phetioDependencies (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PanZoomListener.js:77:64)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM
```

**Comment by jessegreenberg** [comment] 2021-01-08 17:29
This is specifically caused by recent change in https://github.com/phetsims/phet-io/issues/1705, and only is happening in the state wrapper.

**Comment by jessegreenberg** [comment] 2021-01-11 20:55
This should be fixed by https://github.com/phetsims/joist/commit/7628d10241b14fb28fdbf22be7e931da4c67009e, but will leave open until I see it is gone on CT.

**Comment by jessegreenberg** [comment] 2021-01-11 21:56
We have had 2 iterations of CT without this eror, closing.

**Closed by jessegreenberg** 2021-01-11 21:56 UTC
Labels: type:automated-testing
