### ISSUE TITLE
Possible to freeze sliders until page is refreshed on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#340] opened 2020-06-03 22:12 UTC
**Test device**
iPad
**Operating System**
iPadOS 13
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/505.  Seems to be partly an iOS issue, but I wasn't able to reproduce on published. On published the sim did not seem to swipe to go back or forward.
The edges of the sliders to control the masses of objects are on the right side of the screen. If the thumb of the slider is near the edge, and you start to drag it, it is possible for safari to interpret this as moving forward a page. If this starts to happen, but you stay on the sim, then the slider you were attempting to drag will be frozen permanently until you reload the page. Other sliders/items will still respond.
**Steps**
1. Go to the sim
2. Go to a new page in the same tab
3. Swipe to go back to the sim
4. Go to the first screen
5. Move the star mass slider all the way to the right and let go
6. Try to move the slider back towards the left
7. If/when safari starts to move forward a page, let go/move your finger back to stay in the sim
8. Try to interact with the slider

**Visuals**
![backarrow](https://user-images.githubusercontent.com/41024075/83692334-0337bb80-a5b1-11ea-8313-7c4222155dd8.gif)

**Comment by samreid** [comment] 2020-06-08 17:10
In discussion with @arouinfar, we agreed this should be addressed for RC but not necessary for dev version.

**Comment by samreid** [comment] 2020-08-16 16:10
I reproduced the problem on iOS 13.3.1 on an iPad 7.  The slider thumb becomes unresponsive and even "reset all" doesn't bring it back to life.  It looks like it is getting picked up by "swipe to snag".

**Comment by samreid** [comment] 2020-08-16 16:17
I confirmed that adding `allowTouchSnag: false,` to the slider thumb input listener avoids the problem.  My hypothesis is that a snagged object (or perhaps any dragged object) isn't receiving or handling "pointer released" event when using the "swipe browser edge to navigate forward/back".  I'll create a scenery issue for that.

**Comment by samreid** [comment] 2020-08-16 16:21
I opened a scenery issue, putting this one on hold until we have progress in the scenery issue.

**Comment by ariel-phet** [comment] 2020-10-07 00:52
I attempted to reproduce on iOS 14, and I do not see this issue occurring. Also even if this issue still existed I would not consider it a high priority as it is a pretty specific set of steps needed to cause a problem. 

Closing since the iOS update appears to have fixed the issue.

**Closed by ariel-phet** 2020-10-07 00:52 UTC
Labels: priority:2-high, status:on-hold, type:bug
