### ISSUE TITLE
Paths and object positions in state wrapper do not reflect actual positions and paths

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-and-orbits#336] opened 2020-06-01 22:55 UTC
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Chrome Version 83.0.4103.61 

**Problem description**

For https://github.com/phetsims/QA/issues/505

In the States wrapper, when an object is moved, the paths seem to create very jagged lines, as well as display objects crashing into each other which did not occur in the original version of the sim.

**Steps to reproduce**

1. Enter the Model screen
2. Select the Earth and Moon scenario from the righthand side of the screen
3. Check the Paths box
4. Unpause the sim 
5. Manipulate the Earth without destroying the moon

**Visuals**

![2020-06-01Grv OrbitsPhtioState](https://user-images.githubusercontent.com/54685448/83461420-f0dd4680-a425-11ea-9e99-2979f9cbc4a3.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html
Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC
Features missing: generatedcontent, csstransforms3d, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Language: en-US
Window: 1576x776
Pixel Ratio: 1.21875/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment] 2020-06-08 17:03
In discussion with @arouinfar, we agreed: Since a client may want to create an initial condition with a pre-existing path, this should be addressed before next dev version.

**Comment by samreid** [comment] 2020-06-11 01:00
@loganbraywork or @KatieWoe was this behavior improved after the commits in #335 ?

**Comment by KatieWoe** [comment] 2020-06-11 15:41
I'm not able to reproduce on master, but leaving to @loganbraywork to take a look as well.

**Comment by loganbraywork** [comment] 2020-06-16 19:08
The issue appears to be fixed!

**Comment by samreid** [comment] 2020-06-18 04:24
Thanks, closing!

**Closed by samreid** 2020-06-18 04:24 UTC
Labels: status:ready-for-review, type:bug
