### ISSUE TITLE
Destroyed planet still exists and can destroy the moon in the model screen

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/gravity-and-orbits#337] opened 2020-06-02 22:50 UTC
**Test device**

Windows 10 Laptop

**Operating System**

Windows 10 v.1903

**Browser**

Firefox v.76.0.1

**Problem description**

For https://github.com/phetsims/QA/issues/505

This issue does not seem to appear for the moon, planet, star scenario in the "To Scale" screen as it does not seem that the moon can be destroyed by the planet in the "To Scale" screen. This only seems to apply for the "Model" screen. If the planet is destroyed by the star due to colliding into it, the moon will also be destroyed if it moves to the location where the planet last existed.

**Steps to reproduce**

1. Enter the Model screen
2. Select the Star, Planet, & Moon scenario
3. Move the Star, Planet, and Moon so that there is some distance between the three while keeping the simulation paused
4. Move the Star into the Planet, destroying it, and then proceed to move the Star back away from the last location of the Planet
5. Move the Moon to the last location of the Planet

**Visuals**

![2020-06-02Grv OrbitsMoonStarPlanet](https://user-images.githubusercontent.com/54685448/83577297-12efcb00-a4f1-11ea-96d4-c05fe4d3be7a.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html
Version: 1.2.0-dev.10 2020-05-26 17:36:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
Language: en-US
Window: 1568x768
Pixel Ratio: 1.2244897959183674/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment] 2020-06-08 17:05
This seems buggy.  If easy to fix, it should be fixed for the next dev release.  Otherwise, if it should be fixed for RC.

**Comment by samreid** [comment] 2020-06-11 12:49
I pushed a proposed fix, @loganbraywork or @KatieWoe can you please verify on phettest?

**Comment by KatieWoe** [comment] 2020-06-11 15:34
This seems fixed on master. Wasn't able to reproduce on second screen as indicated above, but I'm not sure if that's because it isn't there, or if it is because the elements are so small.

**Comment by samreid** [comment] 2020-06-11 15:37
I think the problem is difficult to create on the 2nd screen because the elements are so small.  Closing.

**Closed by samreid** 2020-06-11 15:37 UTC
Labels: status:ready-for-review, type:bug
