### ISSUE TITLE
Playback speed affects the orbits of closely orbiting bodies

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#253] opened 2016-11-15 20:12 UTC
@arouinfar @jessegreenberg @ariel-phet below is the same setup repeated three times, with each setup only differing in playback speed. It is very obvious that playback speed is affecting the resulting orbits since each orbit is vastly different.

![gao10](https://cloud.githubusercontent.com/assets/5863899/20320183/35fe172a-ab2e-11e6-875f-acb4a3613d07.gif)

Here's some shenanigans on an iPad2, in order of fast, normal, slow:

![gao13](https://cloud.githubusercontent.com/assets/5863899/20321947/79f6eeec-ab34-11e6-9082-fdcb97bdaf55.gif)

![gao12](https://cloud.githubusercontent.com/assets/5863899/20321958/80e657b0-ab34-11e6-87c3-8338d7936d68.gif)

![gao11](https://cloud.githubusercontent.com/assets/5863899/20321961/8852ffc6-ab34-11e6-990e-3b63e01dad2b.gif)

I don't know if this is a floating problem, a dt problem, an fps problem or what, but it really is only obvious when using a setup on the To Scale screen that involves very closely orbiting bodies. The Model screen seems to be fine in similar setups, most likely because the bodies are so large that a collision is nearly guaranteed when when they get too close.

@jessegreenberg, I discussed this with @arouinfar and we agree it is an issue. Can it be addressed easily? @ariel-phet, should time be spent to make orbits consistent between playback speeds?

Seen on macOS 10.12.1 Chrome and iPad2 iOS 9.3.5. For phetsims/tasks#728.

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-rc.1/gravity-and-orbits_en.html
Version: 1.0.0-rc.1 2016-11-11 00:38:23 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36
Language: en-US
Window: 1921x1000
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"HEAD"},"axon":{"sha":"8353fe86","branch":"HEAD"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"HEAD"},"chipper":{"sha":"23f68a56","branch":"HEAD"},"dot":{"sha":"2765eb4d","branch":"HEAD"},"gravity-and-orbits":{"sha":"4d044323","branch":"HEAD"},"joist":{"sha":"76fd7b30","branch":"HEAD"},"kite":{"sha":"48cb255e","branch":"HEAD"},"phet-core":{"sha":"4222a05a","branch":"HEAD"},"phetcommon":{"sha":"2a68c3a8","branch":"HEAD"},"query-string-machine":{"sha":"13ba45df","branch":"HEAD"},"scenery":{"sha":"fb9d77c5","branch":"HEAD"},"scenery-phet":{"sha":"88fdc1dc","branch":"HEAD"},"sherpa":{"sha":"7a7b88b0","branch":"HEAD"},"sun":{"sha":"0e06f113","branch":"HEAD"},"tandem":{"sha":"005c5582","branch":"HEAD"}}

**Comment by phet-steele** [comment] 2016-11-15 20:13
Before you ask, Java has similar problems.

**Comment by ariel-phet** [comment] 2016-11-16 18:31
@jessegreenberg can you comment on your thoughts on what might be causing this discrepancy and how difficult it would be to fix?

**Comment by ariel-phet** [comment] 2016-11-16 18:32
@jessegreenberg as a note if it is seeming tricky to fix, we would probably publish with this as a known issue, and spend some time after publication looking into it more (especially since the behavior exists in Java)

**Comment by jessegreenberg** [comment] 2016-11-16 20:19
This is happening because the model step function is using a delta time that is scaled by play speed.  The step function calculates the next state of all the bodies so play speed is creating varying behavior in the model.

One thing we can try is normalizing the time step applied to the model.  For a given playback speed, we can break up large time steps into a series of uniform (smaller) steps so that behavior is always consistent.  @ariel-phet I will investigate this, but let you know if it looks like it will take a long time to get this working.

**Comment by ariel-phet** [comment] 2016-11-16 20:40
Sounds good @jessegreenberg 

Removing my assignment for the moment

**Comment by jessegreenberg** [comment] 2016-11-16 21:41
With the commit above, the behavior seems consistent for all time steps.  We should verify that this change has not made an impact on performance.

**Comment by jessegreenberg** [comment] 2016-11-16 22:03
Seems OK, but this has somehow introduced (or seriously exacerbated) a memory leak when the path is turned on. On iPad2, it will the bodies will pretty much stop moving after ~20 seconds when the path is turned on.  If visual trace is removed, it all works smooth again.

**Comment by jessegreenberg** [comment] 2016-11-16 22:07
Here is a memory profile on Chrome, where performance is starting to slow down quite a bit:
![snapshot](https://cloud.githubusercontent.com/assets/6396244/20367758/2743dcf2-ac0e-11e6-9e66-56698b3c1303.PNG)

Memory is not too bad yet, so the slowing down is probably coming from the canvas painging.  We can see the arrays on the right have thousands of Vector2's in them, that must be what is slowing everything down.

**Comment by kathy-phet** [comment] 2016-11-17 00:03
Look like you are making progress here. I wanted to mention that if you do publish this sim by Friday morning, please let me know. I am giving a workshop in DC that day and Astronomy faculty will be there, and it would be nice to announce it is published. But I recognize this was a pretty big change so may not be all vetted and published by Friday.

**Comment by jessegreenberg** [comment] 2016-11-17 16:10
Sounds good @kathy-phet, I will let you know.  However, at this point, we will need to go through another RC.  Even if we decide to defer this issue it seems unlikely that the sim will be fully published by Friday morning.

**Comment by jessegreenberg** [comment] 2016-11-17 16:26
I moved https://github.com/phetsims/gravity-and-orbits/commit/1fe84323699d919b7d8663e648738b986369f55f to a test branch because it is a pretty big change, and we might not want to include it yet.

That commit removes the memory leak.  I let the sim run overnight and performance was solid (on Windows Chrome) when I checked this morning.

However, performance is still an significantly worse on tablets.  Normalizing the time step for all play speeds makes both model and view work ~5 times harder at normal speed and ~8 times harder at fast speed.  The extra computations in the model seem fine on an iPad2.  The issue is drawing the traces when the paths are visible.  The paths now have 5-8 times the number of points and tablets start to struggle while drawing when the paths get long.

@ariel-phet we can investigate a workaround for this.  One possibility could be to adjust the resolution of points in the path as a function of play speed and zoom so we don't draw so many points.  But getting to the bottom of this issue could take more time than I initially thought.  Would you like me to continue or should we defer this issue?

**Comment by jessegreenberg** [comment] 2016-11-17 19:42
> I moved 1fe8432 to a test branch because it is a pretty big change, and we might not want to include it yet.

The mem leak fix should be propagated to master, though it is much slower without https://github.com/phetsims/gravity-and-orbits/commit/dc208451df4656a37017fe03f9d2e57a15058ce9 it is still there.

**Comment by ariel-phet** [comment] 2016-11-18 00:28
@jessegreenberg please defer

**Comment by jessegreenberg** [comment] 2016-11-18 17:57
Sounds good, then we should be ready for the next RC.   Removing assignment for now.

**Comment by jessegreenberg** [comment] 2018-02-08 18:09
From #269 - whoever continues work  on this issue should begin by reviewing work in branch uniform-dt.

**Comment by samreid** [comment] 2019-09-03 22:16
The branch is calling `allBodiesUpdated` and hence `addPathPoint` numerous times.  Here is a patch that runs the physics multiple times and updates the path the same number of times.

<details>

```diff
Index: js/common/model/GravityAndOrbitsModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/GravityAndOrbitsModel.js	(revision 1ccf04698970f27e45b023990768145927856069)
+++ js/common/model/GravityAndOrbitsModel.js	(date 1567543148720)
@@ -59,8 +59,8 @@
 
         // NOTE: replacing step with stepModel fixes https://github.com/phetsims/gravity-and-orbits/issues/253
         // but introduces performance issues
-        // this.stepModel( this.clock.dt );
-        this.step( this.clock.dt );
+        this.stepModel( this.clock.dt );
+        // this.step( this.clock.dt );
       } );
 
       // Have to update force vectors when gravity gets toggled on and off, otherwise displayed value won't update
@@ -83,22 +83,28 @@
 
       // standardized time step - based on the slowest time step for the given orbital mode
       const smallestTimeStep = this.clock.getSmallestTimeStep();
+      console.log( smallestTimeStep );
 
       // get the number of times we will need to step the model based on the dt passed in
       const numberOfSteps = dt / smallestTimeStep;
 
       // get the remainder - we must step the model by this at the end so full dt is captured
-      const remainder = dt % smallestTimeStep;
+      // const remainder = 0;
 
       // step the model by the smallest standard time step for the orbital mode
       for ( let i = 0; i < numberOfSteps; i++ ) {
         this.step( smallestTimeStep );
       }
 
+      // Signify that the model completed an entire step so that any batch operations may be invoked
+      for ( let i = 0; i < this.bodies.length; i++ ) {
+        this.bodies[ i ].allBodiesUpdated();
+      }
+
       // if there is a remainder, step by that
-      if ( remainder > 0 ) {
-        this.step( remainder );
-      }
+      // if ( remainder > 0 ) {
+      //   this.step( remainder );
+      // }
     }
 
     /**
@@ -133,11 +139,6 @@
           }
         }
       }
-
-      // Signify that the model completed an entire step so that any batch operations may be invoked
-      for ( let i = 0; i < this.bodies.length; i++ ) {
-        this.bodies[ i ].allBodiesUpdated();
-      }
     }
 
     // @public

```

</details>

I'd like to investigate this further.  If this has reasonable performance on our slowest systems, then it seems good to proceed.  I'd also like to make the slow/normal/fast be integral scale factors, so there is no "remainder" dt as in the branch--which could lead to deviations.

**Comment by samreid** [comment] 2019-09-04 16:03
I'm partway through converting to a playback speed enumeration, and quantizing the speeds.  Here is a patch for me to continue with:

<details>

```diff
Index: js/common/model/SpeedType.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/SpeedType.js	(date 1567610211276)
+++ js/common/model/SpeedType.js	(date 1567610211276)
@@ -0,0 +1,20 @@
+// Copyright 2015-2019, University of Colorado Boulder
+
+/**
+ * Constants that determine how fast the simulation plays.
+ *
+ * @author Sam Reid (PhET Interactive Simulations)
+ */
+define( require => {
+  'use strict';
+
+  // modules
+  const Enumeration = require( 'PHET_CORE/Enumeration' );
+  const gravityAndOrbits = require( 'GRAVITY_AND_ORBITS/gravityAndOrbits' );
+
+  return gravityAndOrbits.register( 'GravityAndOrbitsConstants', new Enumeration( [
+    'SLOW_MOTION',
+    'NORMAL',
+    'FAST_FORWARD'
+  ] ) );
+} );
\ No newline at end of file
Index: js/common/GravityAndOrbitsConstants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/GravityAndOrbitsConstants.js	(revision 1ccf04698970f27e45b023990768145927856069)
+++ js/common/GravityAndOrbitsConstants.js	(date 1567610211279)
@@ -15,7 +15,7 @@
   // constants
   const CONTROL_PANEL_STROKE = '#8E9097';
   const PANEL_X_MARGIN = 5;
-  const STARTING_SPEED_SCALE = ( 0.1 + 2 ) / 4;
+  const STARTING_SPEED_SCALE = 0.525;
 
   const GravityAndOrbitsConstants = {
 
@@ -34,9 +34,9 @@
       scale: 1.05,
       fill: GravityAndOrbitsColorProfile.panelBackgroundProperty
     },
-    STARTING_SPEED_SCALE: STARTING_SPEED_SCALE,
-    FAST_SPEED_SCALE: STARTING_SPEED_SCALE * 1.75,
-    SLOW_SPEED_SCALE: STARTING_SPEED_SCALE * 0.25
+    // STARTING_SPEED_SCALE: STARTING_SPEED_SCALE,
+    // FAST_SPEED_SCALE: STARTING_SPEED_SCALE * 1.75,
+    SLOW_SPEED_OVERALL_SCALE: STARTING_SPEED_SCALE * 0.25
   };
 
   gravityAndOrbits.register( 'GravityAndOrbitsConstants', GravityAndOrbitsConstants );
Index: js/common/model/GravityAndOrbitsModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/GravityAndOrbitsModel.js	(revision 1ccf04698970f27e45b023990768145927856069)
+++ js/common/model/GravityAndOrbitsModel.js	(date 1567609565700)
@@ -99,6 +99,11 @@
       if ( remainder > 0 ) {
         this.step( remainder );
       }
+
+      // Signify that the model completed an entire step so that any batch operations may be invoked
+      for ( let i = 0; i < this.bodies.length; i++ ) {
+        this.bodies[ i ].allBodiesUpdated();
+      }
     }
 
     /**
@@ -133,11 +138,6 @@
           }
         }
       }
-
-      // Signify that the model completed an entire step so that any batch operations may be invoked
-      for ( let i = 0; i < this.bodies.length; i++ ) {
-        this.bodies[ i ].allBodiesUpdated();
-      }
     }
 
     // @public
Index: js/common/module/ModeListParameterList.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/module/ModeListParameterList.js	(revision 1ccf04698970f27e45b023990768145927856069)
+++ js/common/module/ModeListParameterList.js	(date 1567609930063)
@@ -33,6 +33,7 @@
       // @public
       // Flag to indicate if a "rewind" event is taking place, to support storing states for the rewind feature
       this.rewindingProperty = rewindingProperty;
+
       this.timeSpeedScaleProperty = timeSpeedScaleProperty;
     }
   }

```

</details>

**Comment by samreid** [comment] 2019-10-16 17:34
Fixed in the above commits.  I did a few spot checks that the overall behavior is undisturbed, but we will likely need a closer look as we proceed through next round of RC testing.  Closing.

**Closed by samreid** 2019-10-16 17:34 UTC
Labels: dev:model, type:bug

**Comment by samreid** [comment] 2019-11-02 14:59
Note that I also had to increase the single-step dt from 0.525x to 1x in order to maintain reproducible runs when using the step button.
