### ISSUE TITLE
CT value failed isValidValue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#352] opened 2020-07-31 15:01 UTC
```
gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596181443380%7D
Uncaught Error: Assertion failed: value failed isValidValue: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
Error: Assertion failed: value failed isValidValue: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/validate.js:27:18)
at Function.fromStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/types/ArrayIO.js:63:7)
at Star.setStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/Body.js:326:38)
at Function.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/BodyIO.js:30:10)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:415:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:315:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:300:22)
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596188906737%7D
Uncaught Error: Assertion failed: value failed isValidValue: [object Object]
Error: Assertion failed: value failed isValidValue: [object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/validate.js:27:18)
at Function.fromStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/types/ArrayIO.js:63:7)
at Planet.setStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/Body.js:326:38)
at Function.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/BodyIO.js:30:10)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:415:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:315:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:300:22)
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

gravity-and-orbits : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/state/?sim=gravity-and-orbits&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-and-orbits%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596200879667%7D
Uncaught Error: Assertion failed: value failed isValidValue: [object Object],[object Object]
Error: Assertion failed: value failed isValidValue: [object Object],[object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/ValidatorDef.js:307:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/axon/js/validate.js:27:18)
at Function.fromStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/types/ArrayIO.js:63:7)
at Star.setStateObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/Body.js:326:38)
at Function.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/gravity-and-orbits/js/common/model/BodyIO.js:30:10)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:415:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:315:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io/js/PhetioStateEngine.js:300:22)
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM
```

**Comment by jessegreenberg** [comment] 2020-08-03 17:08
I think this is because `Body.path` is expected to be a `Vector2[]` but `Body.setStateObject` 
```js
this.path = ArrayIO( Vector2IO ).fromStateObject( stateObject.path )
```

is setting it to an array of objects that are not `Vector2`s, they just have x and y fields. Or maybe the problem is where the `path` is set in `toStateObject`. I am not sure how to fix, assigning to @samreid for help.

**Comment by samreid** [comment] 2020-08-04 00:47
Thanks @jessegreenberg.  I fixed this with a commit referenced in https://github.com/phetsims/phet-io/issues/1685, closing.

**Closed by samreid** 2020-08-04 00:47 UTC
Labels: type:automated-testing
