### ISSUE TITLE
Return object button does not work 

### ISSUE THREAD

**Issue by bryo5363** [phetsims/gravity-and-orbits#164] opened 2015-09-28 15:31 UTC
Test device: Acer Aspire R13

Operating System: Windows 10

Browser: Chrome latest version

Problem description: The return object button won't work once an object leaves orbit

Steps to reproduce:
open sim
to keep things simple use sun and earth
get earth to escape orbit
the button will appear. clicking on it will not return the object
Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Gravity And Orbits‬
URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-experimental.3/gravity-and-orbits_en.html
Version: 1.0.0-experimental.3 2015-09-24 02:08:59 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Language: en-US
Window: 1280x595
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"1591786f","branch":"master"},"babel":{"sha":"07b67004","branch":"master"},"brand":{"sha":"f2c42d7b","branch":"master"},"chipper":{"sha":"9723adb9","branch":"master"},"dot":{"sha":"99e564e7","branch":"master"},"gravity-and-orbits":{"sha":"71112638","branch":"exponentialDecompositionAlgorithm"},"joist":{"sha":"79243153","branch":"master"},"kite":{"sha":"3a1a5d34","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"acbbf59b","branch":"master"},"scenery":{"sha":"67dce082","branch":"master"},"scenery-phet":{"sha":"6936d39e","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"2d4c4158","branch":"master"}}

**Comment by aaronsamuel137** [comment] 2015-09-28 15:35
This version is buggy since I published in the middle of making some breaking changes so we could have something for design meeting.

If you are going to be testing, stick with experimental.2 and dev.21. Sorry about the confusion with all of these versions!

**Comment by bryo5363** [comment] 2015-09-28 15:38
No worries thanks for the heads up!

**Comment by aaronsamuel137** [comment] 2015-10-06 22:33
Not a bug on master, closing

**Closed by aaronsamuel137** 2015-10-06 22:33 UTC
