### ISSUE TITLE
Playback of recording speeds up and slows down wildly

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#381] opened 2021-03-05 23:09 UTC
For https://github.com/phetsims/QA/issues/595. Seen on MacOS 11 on all three browsers.
When watching the playback of recordings, the speed of the playback slowed down and sped up wildly. It did this in the same parts each time the recording was played back. Some seem connected to attempts to zoom (see https://github.com/phetsims/phet-io/issues/1739). Others seem unrelated. Observe time bar during playback bellow.

https://user-images.githubusercontent.com/41024075/110183763-d2e5ad80-7dcc-11eb-8336-c98b120376dc.MOV

**Comment by zepumph** [comment] 2021-03-08 17:56
I would consider this a duplicate of https://github.com/phetsims/gravity-and-orbits/issues/376. Whatever is causing this is also often causing a large slowdown on startup in the playback. I would recommend only keeping one of the two of these around. See that issue for my thoughts on fixing this issue.

**Closed** 2021-03-16 20:36 UTC
Labels: type:bug
