### ISSUE TITLE
Restart scene buttons may not be included in state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#392] opened 2021-06-23 18:52 UTC
**Device**
Dell
**OS**
Win 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/657. Since this is likely unintended user behavior it may not be worth addressing, but it does seem odd.
When a scene reset button is visible (enabled or not) on a non-active scene, and the sim is launched/saved, the resulting sim does not have those buttons visible.
**Visuals**
![notthere](https://user-images.githubusercontent.com/41024075/123151739-06525380-d421-11eb-8a04-54de1ee569ad.gif)

**Comment by arouinfar** [comment] 2021-06-23 22:38
Well, that's a bit whacky, but I am unable to reproduce on my device. Here's what I tried:

1. Open the rc in studio
2. Search for "SceneResetButton.visibleProperty", and set the first result (belonging to the planet moon scene) to true, and we'll now see 2 scene reset buttons:
![image](https://user-images.githubusercontent.com/8419308/123176648-111ce080-d441-11eb-9445-2691d00d972c.png)
3. Preview sim and the 2nd scene reset button is still visible.

Here's my troubleshooting info (had to open up the phet-brand version to get the "Report a Problem" option in the PhET menu):
> Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_en_phet.html
Version: 1.5.0-rc.1 2021-06-21 17:57:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1440x789
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment] 2021-06-23 22:40
That's odd. If someone wants to pair to work it out let me know.

**Comment by samreid** [comment] 2021-06-29 22:20
The cause of this behavior is in this last line:

```js
      // For the PhET-iO design, we decided to feature the radio button group and leave the reset buttons separate.
      const sceneResetButton = new SceneResetButton( scene, {
        tandem: options.tandem.createTandem( scene.resetButtonTandemName )
      } );

      // link reset buttons so that only the reset button next to the selected radio button is visible
      sceneProperty.link( selectedScene => sceneResetButton.setVisible( selectedScene === scene ) );
```

The `link` resets the visibility of the scene reset buttons, and it does it on a state change.  However, if the `sceneProperty` didn't change, then the link callback is not triggered.  Therefore, the problem can be reproduced like so:

1. Launch studio
2. Search `SceneResetButton.visibleProperty`
3. Toggle the first hit, which is gravityAndOrbits.modelScreen.view.controlPanel.sceneControl.planetMoonSceneResetButton.visibleProperty
4. Press launch.

Here are some possible ways to proceed:
1. Make it so that link does nothing during set state.  That would allow the creator to make a bad state in studio, and launch the bad state.
2. Make it so after set state, the link automatically fires.  That means the creator could create a bad state in studio, then launch would correct it.
3. Leave it as it is now
4. Find a way to make it more difficult for the creator to create a bad state in the first place.

@arouinfar can you please advise?

**Comment by arouinfar** [comment] 2021-06-30 18:25
@samreid when I follow these steps, the state of the previewed sim matches studio (two visible scene reset buttons), which is not what @KatieWoe originally reported.
> 1. Launch studio
>2. Search `SceneResetButton.visibleProperty`
>3. Toggle the first hit, which is gravityAndOrbits.modelScreen.view.controlPanel.sceneControl.planetMoonSceneResetButton.visibleProperty
>4. Press launch.

That said, I think we can leave things as they are now. I don't think we need to start looking for/correcting bad states.

**Comment by samreid** [comment] 2021-06-30 20:24
Yes, I'm seeing the same thing and it makes sense from the explanation above.  I agree we don't need a correction here, closing.

**Closed by samreid** 2021-06-30 20:24 UTC
Labels: type:bug
