### ISSUE TITLE
Step back time/position not saved in state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#424] opened 2022-06-28 17:32 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/816.
If you set a new position for the step back button, then set the state, the new position is not saved in state. Instead, the set back time/position seems to always be set at what it was when state was set.
**Steps to reproduce**
1. Go to the state wrapper
2. Go to the first screen
3. Set the refresh rate to 0
4. In the top sim, move an object while paused so that the step back time/position is reset
5. Play the top sim for a short time so objects are in new places
6. Set state

**Visuals**
<img width="437" alt="stateofjumpback" src="https://user-images.githubusercontent.com/41024075/176246055-56d38b0d-0c53-40ad-b5ff-683b94484a89.png">

**Comment by samreid** [comment] 2022-06-29 02:20
It looks like the same problem is present in the previous version https://phet-io.colorado.edu/sims/gravity-and-orbits/1.5/wrappers/state/, so this is not a regression and may also not be a blocking issue.

**Comment by Nancy-Salpepi** [comment] 2022-07-05 13:22
I believe this is the same issue as https://github.com/phetsims/gravity-and-orbits/issues/415

**Comment by Nancy-Salpepi** [comment] 2022-07-05 13:28
Sorry! Deleted last comment as I realized it was a different issue!

**Comment by samreid** [comment] 2022-08-08 20:57
The current behavior was designed for https://github.com/phetsims/gravity-and-orbits/issues/343.  I tried commenting out that solution:

<details>

```diff
Index: js/common/GravityAndOrbitsScene.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/GravityAndOrbitsScene.ts b/js/common/GravityAndOrbitsScene.ts
--- a/js/common/GravityAndOrbitsScene.ts	(revision 96266559f17339bc89142ce49de844e450e7def3)
+++ b/js/common/GravityAndOrbitsScene.ts	(date 1659991926704)
@@ -200,16 +200,16 @@
 
     // Save the new PhET-iO state as an initial configuration for this scene, but only if the state being set applies
     // to this scene.
-    Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( ( state: Record<string, unknown> ) => {
-
-      const phetioIDsToSet = Object.keys( state );
-      for ( let i = 0; i < phetioIDsToSet.length; i++ ) {
-        if ( phetioIDsToSet[ i ].startsWith( this.tandem.phetioID ) ) {
-          this.saveState();
-          break;
-        }
-      }
-    } );
+    // Tandem.PHET_IO_ENABLED && phet.phetio.phetioEngine.phetioStateEngine.stateSetEmitter.addListener( ( state: Record<string, unknown> ) => {
+    //
+    //   const phetioIDsToSet = Object.keys( state );
+    //   for ( let i = 0; i < phetioIDsToSet.length; i++ ) {
+    //     if ( phetioIDsToSet[ i ].startsWith( this.tandem.phetioID ) ) {
+    //       this.saveState();
+    //       break;
+    //     }
+    //   }
+    // } );
   }
 
   /**

```

</details>

And saw the behavior was as expected for this issue.  However, with commenting out this code, the behavior in https://github.com/phetsims/gravity-and-orbits/issues/343 will no longer work.  @arouinfar can you please advise which behavior is preferable, or if we need some way to distinguish and try to get each behavior in a certain situation?

**Comment by arouinfar** [comment] 2022-08-08 21:44
I think the current behavior is as expected, and the solution designed for #343 is preferable.

I think it would be strange for the RestartButton to return a state that existed before the state was saved. The goal for this button is to allow users to repeat an experiment (requires the sim to be paused), with the startup/default state being the fallback. In the case described by @KatieWoe, there was never an experiment performed in the downstream sim so the RestartButton returns the simulation to its startup state. I do not find it problematic that the upstream and downstream sims return different states when the RestartButton is pressed.

I think we can go ahead and close this issue @samreid.

**Closed by arouinfar** 2022-08-08 21:44 UTC
Labels: type:bug
