### ISSUE TITLE
Letters jump around in Firefox

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#80] opened 2014-01-13 22:36 UTC
Test device: Lenovo Z585

Operating System: Windows 8 64-bit

Browser: Firefox 26

Problem description: The letters in the sim jump around while it is running in Firefox. This is most obvious while playing the sim with an increased planet size in the Planet+Star orbit of the Cartoon scene. However, the letters STOP jumping when the velocity vectors are turned on, then revert back to jumping when the vectors are turned off. The jumping also occurs while doing various other things throughout the sim. Perhaps this is a performance issue?

Steps to reproduce:
1. Open the sim and select the Cartoon scene.
2. On the Planet+Star orbit, increase the planet size to max and press play.

Severity: Low, doesn't have an effect on physics and the sim still runs at a decent speed (decent for Firefox at least).

Screenshots:

Troubleshooting information (do not edit):

Name: Gravity and Orbits

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.9/gravity-and-orbits_en.html

Version: 1.0.0-dev.9

Features missing: flexbox, touch

User Agent: Mozilla/5.0 (Windows NT 6.2; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0

Language: en-US

Window: 1366x641

Pixel Ratio: 1/1

WebGL: disabled

**Comment by aaronsamuel137** [comment] 2015-09-18 16:28
Can't reproduce this in the rewrite. I'l leave it open in case testers can.

**Comment by ariel-phet** [comment] 2016-06-17 15:55
No longer seems to be an issue. Closing

**Closed by ariel-phet** 2016-06-17 15:55 UTC
