### ISSUE TITLE
Sun disappears after 8500 days

### ISSUE THREAD

**Issue by samreid** [phetsims/gravity-and-orbits#152] opened 2015-09-21 16:48 UTC
While testing a number of things with @aaronsamuel137 I noticed that the sun disappeared sometime around 8500 days.  May be attributable to my numerous working copy changes for testing performance, but maybe something else.  We should just test cartoon mode+ sun/earth and see if it happens again.

**Comment by phet-steele** [comment] 2015-09-21 17:27
This was not occurring for me after ~35700 days in 1.0.0-experimental.2. Instead, the Earth was doing a sort of slow spiral that ended with the orbit getting smaller and smaller until crashing into the sun. Most likely a separate issue, will look further into this and 1.0.0-dev.21.

![gao](https://cloud.githubusercontent.com/assets/5863899/9999441/ad6a3bf8-6053-11e5-8962-03d721a145c7.gif)

**Comment by phet-steele** [comment] 2015-09-21 17:48
Neither of these issues are happening for me in 1.0.0-dev.21.

**Comment by aaronsamuel137** [comment] 2015-10-07 17:23
Can't reproduce this. Assuming it was a fluke due to working changes and closing. We can reopen if it happens again.

**Closed by aaronsamuel137** 2015-10-07 17:23 UTC
