### ISSUE TITLE
sim fails when a screen is selected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/gravity-and-orbits#139] opened 2015-02-24 00:58 UTC
This is with master, all platforms. Start the sim in requirejs mode, select one of the screens, and you'll see a bunch of errors in the console, see screenshot below. The sim is dead at this point.

![screenshot_471](https://cloud.githubusercontent.com/assets/3046552/6341219/798dadb0-bb85-11e4-89dd-ab28ffec1836.png)

**Comment by pixelzoom** [comment] 2015-03-03 21:56
This is still a problem, guessing it's scenery related, assigning to @jonathanolson.

**Comment by jonathanolson** [comment] 2015-03-03 23:28
I can't even get to that point, the setTranslation() in MassMenu (line 46) triggers an assertion before that, and may be the cause of this problem.

I'm reassigning to @aaronsamuel137, I'm not sure how much of the code we're planning on keeping (and how much effort should be put into ironing this out).

**Comment by aaronsamuel137** [comment] 2015-03-04 17:46
I've merged in the direct port branch to master. This issue no longer happens now - though much of the view remains to be ported still.

**Comment by aaronsamuel137** [comment] 2015-03-04 17:49
Closing this issue since the sim launches now. GAO still needs a lot of work before it is ready to be tested.

**Closed by aaronsamuel137** 2015-03-04 17:49 UTC
Labels: bug
