### ISSUE TITLE
Diff wrapper does not show difference between 1.5 and 1.6

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-and-orbits#423] opened 2022-06-27 18:23 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/816.
In the diff wrapper for 1.6, entering the url for 1.5 shows no results and the console shows the errors shown bellow.

**Visuals**
<img width="959" alt="nodiff" src="https://user-images.githubusercontent.com/41024075/176009384-dc67ed76-1073-493f-88d8-224b8301042a.png">

**Comment by KatieWoe** [comment] 2022-06-27 18:28
I got the same error when trying to compare 1.6 to itself.

**Comment by KatieWoe** [comment] 2022-06-29 22:47
This also happens in Firefox

**Comment by KatieWoe** [comment] 2022-07-07 22:39
That does seem to work for the old version. Typing 1.6 to try to compare it to itself does not work though.
I also see this in https://github.com/phetsims/qa/issues/818

**Comment by zepumph** [comment] 2022-07-13 20:18
We will investigate why we can't load 1.6 and compare it to 1.6.

**Comment by samreid** [comment] 2022-08-03 02:38
I believe this answer is straightforward. It is able to load prior versions because the API file for the prior versions is published on the phet-io website at a standard location. Since we are testing a dev or RC version for 1.6, there is no API file for the production version of 1.6 at the standard location, therefore the comparison cannot be made. I believe this is an acceptable and useful constraint that does not need to be documented because it will not impact our clients. Once we have published a production version of 1.6, I would expect it to be able to compare to itself. But we will not be able to test that until we publish a production version.

@zepumph OK to close?  Or do you want a spot check after publication?

**Comment by zepumph** [comment] 2022-08-03 21:15
Recent changes to the diff wrapper have caused us to not be able to just diff two arbitrary links. In my opinion that is a regression that was not necessary, and not that beneficial. I agree that this error is "acceptable" because it won't effect clients, but why would we set up our wrapper to not be able to diff against a version in an RC. It just seems like we are asking to have to do more work later.

**Comment by samreid** [comment] 2022-08-03 22:46
Client.getAPIFile currently takes a version.  Do you recommend that getAPIFile would take version|URL?  Or two methods, like `getAPIFileForVersion` and `getAPIFileForURL`?

I also tried entering 1.6.0-dev.2 for the comparison and it said APIs are identical.  Is that acceptable for now?  Is this work blocking the upcoming release?

<img width="876" alt="image" src="https://user-images.githubusercontent.com/679486/182725209-0bef5dbb-b32e-47e9-ad9c-fd60f7a375ea.png">

**Comment by samreid** [comment] 2022-08-09 22:27
@zepumph and I discussed that we have utilities for comparing API files from specific URLs such as dev versions.  We can download them and run grunt compare-phet-io-api or something.  This wrapper seems good enough for clients and no more work is needed for this milestone, closing.

**Closed by samreid** 2022-08-09 22:27 UTC
Labels: type:bug, priority:2-high, status:ready-for-review, dev:phet-io
