### ISSUE TITLE
[iPad 2] Performance when switching orbits

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#220] opened 2016-09-27 19:18 UTC
Really the performance on iPad 2 is bad all around, but it is at its worst when switching between sim states (orbits/screens). This video was captured just after sim load (no fancy checkboxes enabled):

https://drive.google.com/file/d/0B3HJopSo_QqLb1pKZHlSVW5ySzg/view?usp=sharing

Tested on iPad 2 iOS 9.3.5. For phetsims/tasks/issues/692.

URL: http://www.colorado.edu/physics/phet/dev/html/gravity-and-orbits/1.0.0-dev.30/gravity-and-orbits_en.html
Version: 1.0.0-dev.30 2016-09-08 16:14:29 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Language: en-us
Window: 1024x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"cf925265","branch":"master"},"babel":{"sha":"da2eb7f1","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"5c755230","branch":"master"},"dot":{"sha":"23b13772","branch":"master"},"gravity-and-orbits":{"sha":"19a982e6","branch":"master"},"joist":{"sha":"c0442ba8","branch":"master"},"kite":{"sha":"3b656b9a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"83ea84c8","branch":"master"},"scenery":{"sha":"cee9ad57","branch":"master"},"scenery-phet":{"sha":"799d6f8d","branch":"master"},"sherpa":{"sha":"cd023acf","branch":"master"},"sun":{"sha":"c22a4261","branch":"master"},"tandem":{"sha":"4a8edbc9","branch":"master"}}

**Comment by jessegreenberg** [comment] 2016-09-28 22:10
> Really the performance on iPad 2 is bad all around

@phet-steele could you please clarify? I am running the sim on Witten (iOS 9.3.5) and performance seems good, other than the specific issue you pointed out.

> but it is at its worst when switching between sim states (orbits/screens).

Yes, I can see that on Witten.  I also reproduced on Chrome, but to a lesser extend, and only for the built version.

**Comment by phet-steele** [comment] 2016-09-29 17:10
@jessegreenberg not much to clarify, my opinion was that its overall performance wasn't great. Mostly with the jerkiness in the orbits, and zooming felt a tad slow.

**Comment by jessegreenberg** [comment] 2016-10-24 20:21
The root cause of this is the excludeInvisible: true option added to GravityAndOrbitsPlayArea.

It removes invisible layers from the DOM.  Here is the blockSummary with excludeInvisible: true
![capture](https://cloud.githubusercontent.com/assets/6396244/19662482/ead9b3c0-99f4-11e6-85f0-d82ea65cfbfc.PNG)

And the block summary with excludeInvisible: false
![exclude false](https://cloud.githubusercontent.com/assets/6396244/19662491/f35a505e-99f4-11e6-8cf1-c8bb2e842286.PNG)

The extra canvas and svg blocks look like bade news.  But performance seems fine on iPad2.  Is performance worse on other platforms?

**Comment by jessegreenberg** [comment] 2016-10-24 20:40
Consulted with @jonathanolson, removing the excludeInvisible flag is fine as long as sim doesn't crash due to memory limitations.

Tested on Chrome, Firefox, and iPad2 Safari, sim does not crash so this seems like a fine solution.

There is still a long delay on all platforms for the built version when toggling screen views.  This only happens the first time on chrome, so it is able to cache something.

**Comment by jessegreenberg** [comment] 2016-10-24 20:43
Delay for RequireJS version is ~0.5 seconds.  Delay for built version is ~3.5 seconds.

**Comment by jessegreenberg** [comment] 2016-10-24 20:46
Removing the canvas does nothing to improve performance.

**Comment by jessegreenberg** [comment] 2016-10-25 16:27
Time is reduced quite a bit when replacing all images with moons.

**Comment by jessegreenberg** [comment] 2016-10-25 17:41
Removing the excludeInvisible flag hurts performance in Chrome by quite a bit, and causes Chrome to take ~15% cpu while the sim is running.

**Comment by jessegreenberg** [comment] 2016-10-25 17:45
Moving excludeInvisible to the PathsCanvasNode instead of GravityAndOrbitsPlayArea returns performance to chrome.  Not sure if this brings back the delay in switching orbits yet.

**Comment by jessegreenberg** [comment] 2016-10-25 17:47
> Not sure if this brings back the delay in switching orbits yet.

It does not, so excludeInvisible should be located on the PathsCanvasNode.

**Comment by jessegreenberg** [comment] 2016-10-25 17:53
Back to https://github.com/phetsims/gravity-and-orbits/issues/220#issuecomment-256086446, the moons images are very small in size, so this could be a memory issue, but not sure.

**Comment by jessegreenberg** [comment] 2016-10-25 18:41
This is not an issue for dev.28, which has all the updated assets.  But isolating in dev.29 could help narrow down the cause.

**Comment by jessegreenberg** [comment] 2016-10-25 18:46
~16 commits between the two versions. e0811318a5033f702f7016757097404ed03d233f to d38517222116a21507e17e281a6e178a6b186443.

**Comment by jessegreenberg** [comment] 2016-10-25 18:55
c3e2049555d8fec70ffa2b343b1590b9433665e5 from #208 looks suspicious.

**Comment by jessegreenberg** [comment] 2016-10-25 22:05
I ended up reverting https://github.com/phetsims/gravity-and-orbits/commit/24dda058fab305e942fb3557acd9a767783f9dea because it seemed to reduce performance in Chrome when the paths were turned on.

The commit above reduces the image quality of the earth a bit and this improves performance by quite a bit.  The file size of the earth image was about as large as all of the images in Energy Forms and Changes combined.

**Comment by brroberts1231** [comment] 2016-11-01 16:54
Looks good to me, closing

**Closed by brroberts1231** 2016-11-01 16:54 UTC
Labels: status:ready-to-test, type:performance
