### ISSUE TITLE
Experimental Death Spiral

### ISSUE THREAD

**Issue by phet-steele** [phetsims/gravity-and-orbits#154] opened 2015-09-21 22:36 UTC
This issue was originally a comment in #152. In 1.0.0-experimental.2, the Earth/Sun and Earth/Moon/Sun orbits have the Earth slowly spiraling into the sun. I saw this in the cartoon orbits ONLY. This may very well be in the orbits on the To Scale screen, but may take billions upon billions of sim years to witness. Here is the end of the spiral, at around 35700 sim days:

![gao](https://cloud.githubusercontent.com/assets/5863899/10006718/e6a09628-607c-11e5-9287-ce3eeabca908.gif)

This is done by just pressing play and waiting for awhile. This was tested on Win 8.1 Chrome 45.

**Comment by aaronsamuel137** [comment] 2015-10-07 17:42
I can't reproduce this on current master. Perhaps it was fixed when addressing other issues?

<img width="1062" alt="screen shot 2015-10-07 at 11 40 32 am" src="https://cloud.githubusercontent.com/assets/3193912/10345629/4a599864-6ce8-11e5-8318-3b2d3158a95c.png">

Everything looks good at 36000 days.

I'm closing the issue. Feel free to reopen @phet-steele if you reproduce this again.

**Closed by aaronsamuel137** 2015-10-07 17:42 UTC
Labels: experimental
