### ISSUE TITLE
"Planet" label disappears when mass is increased and zoomed in

### ISSUE THREAD

**Issue by stemilymill** [phetsims/gravity-and-orbits#393] opened 2021-06-23 20:05 UTC
Test device
Dell
Operating System
Win 10
Browser
Chrome
Problem description
For phetsims/QA#657
In the planet-moon scene, if the planet mass is 1.25 earths or greater, the "Planet" label disappears when zoomed in, comes back when zoomed out again.

Steps to reproduce
Go to the second screen
Go to the planet-moon scene
Increase planet mass to 1.25 Earth masses or greater
Zoom in until "Planet" label disappears

Visual

![planet label disappears when it heavy](https://user-images.githubusercontent.com/85511101/123160376-19265180-d43c-11eb-9c8a-b40adf819a07.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Gravity and Orbits‬
URL: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_all_phet.html
Version: 1.5.0-rc.1 2021-06-21 17:57:44 UTC
Features missing: applicationcache, generatedcontent, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
Language: en-US
Window: 1536x754
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by samreid** [comment] 2021-06-27 22:52
Apparently the label is only supposed to show if the view diameter of the body is below a certain threshold, as seen in https://github.com/phetsims/gravity-and-orbits/issues/243.  Changing the mass or zoom level can change the view diameter.  So, even though this seems odd in this case, perhaps it is by design.  @arouinfar can you please comment?

**Comment by arouinfar** [comment] 2021-06-28 17:58
@samreid let's bump up the diameter threshold up to 12.  In local testing, I'm unable to dismiss the label on the bodies in the To Scale screen by zooming, and the behavior still looks good on the Model screen.

**Comment by samreid** [comment] 2021-06-28 18:02
I increased the threshold to 12, can you please review?

**Comment by arouinfar** [comment] 2021-06-28 18:30
Thanks @samreid, looks good.

**Comment by samreid** [comment] 2021-07-05 18:37
I added a cherry-pick commit, ready for testing when RC.2 is published.

**Comment by samreid** [comment] 2021-07-13 18:30
This can be tested by:

Steps to reproduce
Go to the second screen
Go to the planet-moon scene
Increase planet mass to 1.25 Earth masses or greater
Zoom in and make sure labels do not disappear.

**Comment by stemilymill** [comment] 2021-07-13 19:14
labels did not disappear in master

**Comment by samreid** [comment] 2021-07-13 19:15
Thanks!  For issues like these, I recommend closing when they have been confirmed fixed in RC.2.  Then when the milestone list https://github.com/phetsims/gravity-and-orbits/milestone/4 is empty, we are ready to publish.  Sound OK?

**Comment by stemilymill** [comment] 2021-07-13 19:23
Yes! I hadn't seen the RC spot check issue yet, I'll go check this off over there

**Closed** 2021-07-13 21:32 UTC
Labels: status:ready-for-qa, type:bug
