### ISSUE TITLE
Unused string keys

### ISSUE THREAD

**Issue by arouinfar** [phetsims/gravity-and-orbits#438] opened 2022-09-19 16:45 UTC
For #440 

When reviewing the strings in Studio, I realized that there are two unused string keys --  `earthDayStringProperty` & `earthMinuteStringProperty`. These are both singular versions of the timeCounter string,  however, only the plural version is ever used in the sim.
<img width="136" alt="image" src="https://user-images.githubusercontent.com/8419308/191069334-62e10b8a-eac2-493d-a681-615837d791cc.png">  <img width="153" alt="image" src="https://user-images.githubusercontent.com/8419308/191069378-fe025af2-2e48-43dd-b783-efc4410dcc20.png">

@samreid can you confirm if these string keys are being used somewhere in the sim? If not, can we get rid of them?

**Comment by samreid** [comment] 2022-09-26 21:43
I fixed this code and it should now be using the singular strings.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/679486/192386058-3fd3c8ca-b96e-493c-943b-783b402b8cf2.png">

@arouinfar can you please review?

**Comment by arouinfar** [comment] 2022-09-29 19:06
Thanks @samreid. Looks good in master, but not in rc.1, so tagging for cherry-picking.

**Comment by samreid** [comment] 2022-10-06 04:04
Needed for https://github.com/phetsims/qa/issues/841

**Comment by samreid** [comment] 2022-10-07 15:39
We pushed a fix in https://github.com/phetsims/gravity-and-orbits/issues/463 and @marlitas and I confirmed the strings are correctly omitted.  Leaving open for verification in RC after cherry-picking.

**Comment by samreid** [comment] 2022-11-09 00:51
Please close after verifying.

**Comment by KatieWoe** [comment] 2022-11-10 19:40
This seems to be broken again in https://github.com/phetsims/qa/issues/850
![notfixed2](https://user-images.githubusercontent.com/41024075/201190545-ac74a5d8-7b04-46fc-bd93-54c6d1dfddf2.png)
![notfixed](https://user-images.githubusercontent.com/41024075/201190546-00cd0246-8483-4370-845a-5362c22192ac.png)

**Comment by Nancy-Salpepi** [comment] 2022-11-10 19:46
@KatieWoe they decided to always go back to always plural because of https://github.com/phetsims/gravity-and-orbits/issues/463

**Comment by samreid** [comment] 2022-11-10 21:30
From discussion with @KatieWoe 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/679486/201209921-75e877fc-29d2-486a-98a3-a2a11775dc92.png">

**Comment by KatieWoe** [comment] 2022-11-11 17:28
Closing. Looks ok in RC 4

**Closed by KatieWoe** 2022-11-11 17:28 UTC
Labels: type:bug
