### ISSUE TITLE
publish PhET-iO dev version for the client

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-and-orbits#345] opened 2020-06-04 21:18 UTC
We are not quite ready for this issue I think, but I thought I would take new documentation for a test drive in this repo. Here is the issue:

@kathy-phet would like to deliver a PhET-iO dev version of gravity and orbits to the client for review.

1. - [x] Determine what sim specific issues need to be done before publishing the dev version.
2. Look at open issues labeled "status:blocks-publication". Determine which need to be done for this release, and which can wait until RC. 
    * Here is the list of issues that need to be done for this dev release:
      - [x] . . . 
    * Here is the list of issues that are currently marked as "status:blocks-publication" but don't need to be done for this dev version:
      - [x] . . . 
3. - [x] Dev test the simulation. Create a QA dev test template issue and include the PhET-iO section.
4. - [x] Address issues that come out of testing. Triage with your designer, as it is possible that not all need to be addressed for the dev version. 
5. - [x] @samreid: publish dev versions, add links to this issue
6. - [x] @arouinfar: review and sign off
7. - [ ] @kathy-phet: delivery to the client 

Note that for (2), there is a good chance that this will be a similar list as in (2) in https://github.com/phetsims/states-of-matter/issues/296#issuecomment-639105083

**Comment by samreid** [comment] 2020-07-20 17:34
@arouinfar and I triaged issues, and the only remaining issues are scheduled for RC and not necessary for dev.  I reviewed the general blocks-publication issues and they don't seem like they would disturb a dev version.

I published this dev version.

Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.11/phet/gravity-and-orbits_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.11/phet-io/

@arouinfar can you please spot check these versions?  If they seem OK to you, I'll open a QA dev test issue.  If that checks out, we can deliver this dev version to the client.

**Comment by arouinfar** [comment] 2020-07-21 06:21
@samreid I spot tested the dev version, and it seems to be in working order. However, this version was published before I finished the [client guides](https://github.com/phetsims/phet-io-client-guides/blob/master/gravity-and-orbits/). Would it be relatively straightforward publish a new dev version for QA testing so the guides get picked up in the build?

**Comment by samreid** [comment] 2020-07-21 13:48
Here is a new version that includes the client requests and guide:

https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.12/phet/gravity-and-orbits_en_phet.html
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.12/phet-io/

I took a quick glance at them and did not see any obvious problems.  At this point, I'd like to create a QA issue to get it scheduled in the pipeline.  But I'm also leaving assigned to @arouinfar for a spot check for dev.12 -- please let me know right away if something is out of order and I'll invalidate or update the QA issue.

**Comment by samreid** [comment] 2020-07-21 14:54
I created the QA issue, linked above.

**Comment by arouinfar** [comment] 2020-07-30 00:18
@samreid I reviewed this last week (but forgot to comment/close), and everything was looking good.

**Comment by samreid** [comment] 2020-07-30 00:21
I recommend to leave this open until the dev version has been delivered to the client.

**Comment by samreid** [comment] 2020-11-02 23:15
The only common code issue pertinent to this deploy is https://github.com/phetsims/chipper/issues/787.  @jessegreenberg and I discussed and @jessegreenberg recommended:

> I would probably revert for for your publication since the issue did not manifest itself in GAO, and this change may have an unintended consequence. But leave in master with blocks-publication until JO can review behavior.

So I'll create RC.1 from master, then make a maintenance release to revert the chipper changes.

**Comment by samreid** [comment] 2020-11-02 23:36
I published these versions and will update the "RC-lite" issue:

Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet/gravity-and-orbits_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-rc.2/phet-io/

**Comment by samreid** [comment] 2020-11-14 16:37
All blocks-publication issues are cleared.  I ran a `grunt rc` command for 1.3, but it doesn't look like the build is completing (at least after 5 minutes).

**Comment by samreid** [comment] 2020-12-04 20:28
I asked on slack:

> This is my first experience delivering an RC-Lite version to a client.  Do we give them a link to an RC, or do we publish a production version?  If we publish a production version, how do we prevent it from being published on the main site?

**Comment by samreid** [comment] 2020-12-04 20:39
On slack @zepumph said:

> I thought that RC LIte was delivered through phet-dev. Let me check the docs.
> We still haven't updated the docs from "initial dev version" to "rc lite", which makes me more confident that we just deliver from phet-dev: https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-technical-guide.md#initial-dev-release-to-client

I asked:
> Does “deliver from phet-dev” mean I give the link to an RC version?
> Or I somehow publish a production version on phet-dev?

@zepumph replied:
> just an RC version.

**Comment by samreid** [comment] 2020-12-04 20:45
All issues discovered during QA lite were confirmed in the RC.3 or determined to be unnecessary for this release.  So https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.3/phet-io/ is ready to deliver to the client.

**Comment by samreid** [comment] 2020-12-04 22:02
I captured some slack discussion in a private issue.

**Comment by samreid** [comment] 2020-12-11 22:44
I believe @kathy-phet delivered a dev version (the RC) to our client.  Closing.

**Closed by samreid** 2020-12-11 22:44 UTC
Labels: priority:2-high, status:ready-for-review
